### PR TITLE
refactor: better repository structure

### LINKED ISSUE #28: dis_rs_macros is still necessary?
Is `dis_rs_macros` still necessary? I've not found any reference to it in `dis-rs`

### PR DESCRIPTION
**Pull request by carlocorradini**
**WIP**
Improving overall repository structure, code, CI, CD and more...
Automatic release when pushing a semver tag (`v1.0.0`), after CI is successfull and (of course) CD.
Automatic LICENSE year update (license.yaml) workflow

Fix #28 #29 #30 (and more?)

TODO:
- [ ] Fix `cargo fmt`
- [ ] Fix `cargo clippy`
- [ ] Add `check.yaml` for CI
- [ ] Add `release.yaml` for CD

### CODE REVIEW

**Comment by zlubsen** [comment]
Regarding restructuring the repository structure, I'm seeing this repo as a mono repo that contains several related libraries and binaries.
Work is ongoing on a Compressed-DIS (C-DIS) implementation. That already covers two crates/projects in addition to the current dis-rs/dis-rs crate.

It will be a suite containing something like this:

- dis-rs: library that models PDUs and parse/serialize functionality (current dis-rs lib)
- cdis-assemble: library that models C-DIS PDUs and parse/serialize functionality (work in progress)
- cdis-gateway: application that can encode/decode DIS to C-DIS and vice versa (work in progress)
- cdis-integrate: library that provides functionality to integrate the encoding/decoding into an application (currently in cdis-gateway, to be extracted)
- dis-integrate: library that provides functionality to integrate DIS into a simulation application. I.e. you feed the library host simulation data and set configuration such as the EntityId, and the library handles putting the right PDUs on the wire at the right moment, handles dead reckoning, etc. (planned)
- eventually monitoring tools... (along the lines of suites like https://redsim.com)

Currently no thoughts yet on how to do versioning between the projects, etc.

**Comment by carlocorradini** [comment]
Fantastic 🥳
Why not combine the master branch and the c-dis branch?
It would be ideal to see those on the master branch if you believe that the work in the branch will impact this repository in the future (with further improvements).

**Comment by zlubsen** [comment]
It will be merged the coming week or so, the CDIS branch is coming towards  a basic/usable state.

**Comment by carlocorradini** [comment]
Awesome 😎

**Pull request closed without merging**
